In [1]:
import pandas as pd
import numpy as np

In [2]:
sigmoid = lambda z: 1./(1+np.exp(-z))

In [3]:
# x_train (1, 2)
x_train = np.ones((1, 2))
y_train = np.ones((1, 1))

w1 = np.array([[-2, -3], [2, 3]])  # (2, 2)
w2 = np.array([[-2, -3], [2, 3]])  # (2, 2)
w3 = np.array([2, -1.5])  # (1, 2)

b1 = np.array([-1, 1])  # (1, 2)
b2 = np.array([-1, 1])  # (1, 2)
b3 = np.array([-1])     # (1, 1)

In [4]:
z1 = np.dot(x_train, w1.transpose()) + b1
a1 = sigmoid(z1)
z2 = np.dot(a1, w2.transpose()) + b2
a2 = sigmoid(z2)
y = np.dot(a2, w3.transpose()) + b3
L = 0.5*np.square((y-y_train))

In [5]:
print(f'a1 = {a1}\na2 = {a2}\ny  = {y}')

a1 = [[0.00247262 0.99752738]]
a2 = [[0.01802994 0.98197006]]
y  = [-2.43689523]


In [6]:
dldy  = y - y_train
dldb3 = float(dldy.sum())
dldw3 = np.dot(dldy.transpose(), a2)

dldz2 = dldy*w3.transpose() * a2 * (1 - a2)
dldb2 = dldz2.sum(axis=0)
dldw2 = np.dot(dldz2.transpose(), a1)

dldz1 = np.dot(dldz2, w2) * a1 * (1 - a1)
dldb1 = dldz1.sum(axis=0)
dldw1 = np.dot(dldz1.transpose(), x_train)

In [7]:
print(f'dl/db3 =\n{dldb3}\n\ndl/dw3 =\n{dldw3}')
print(f'dl/db2 =\n{dldb2}\n\ndl/dw2 =\n{dldw2}')
print(f'dl/db1 =\n{dldb1}\n\ndl/dw1 =\n{dldw1}')

dl/db3 =
-3.436895226556018

dl/dw3 =
[[-0.061967   -3.37492823]]
dl/db2 =
[-0.12169947  0.09127461]

dl/dw2 =
[[-0.00030092 -0.12139856]
 [ 0.00022569  0.09104892]]
dl/db1 =
[0.00105061 0.00157591]

dl/dw1 =
[[0.00105061 0.00105061]
 [0.00157591 0.00157591]]


In [8]:
r = 0.001
b3 = b3 - r*dldb3
w3 = w3 - r*dldw3
b2 = b2 - r*dldb2
w2 = w2 - r*dldw2
b1 = b1 - r*dldb1
w1 = w1 - r*dldw1